# Generated by Django 4.2 on 2024-06-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_products_shirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='medal',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(help_text='Poner el nombre así y sólo como está escrito en el artículo', max_length=150, unique=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, default='https://www.pornhub.com/information/terms#faq', max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
    ]
